### ISSUE TITLE
Allow external barcode scanner app => improve camera/scanner handling

### ISSUE THREAD

**Issue by stacsk** [tfonteyn/NeverTooManyBooks#181]
Hello. My camera is not detecting the barcodes for some reason but I could easily scan with Atharok's [Barcode Scanner](https://gitlab.com/Atharok/BarcodeScanner), for instance, when I used Book Catalogue. Could you maybe add external app support for scanning?

Thank you for your work.

**Comment by tfonteyn** [comment]
Atharok is using the same barcode scanner library as I do:  [zxing ](https://github.com/zxing/zxing )version "3.3.3" while I'm using the latest version '3.5.3'
We're using the same Android CameraX library, same version.

While technically possible to call an external app, I see no point doing so if we're using the same libs anyhow.

What I can do however is review my use of camera settings and see if I can improve on them.
Give me some time to review the Atharok  parameter usage in depth and I'll see if/how I can improve mine.

One tip (which I really should add to my docs) is to switch on the "torch" using the icon at the bottom of the scan screen. I find lack of light the biggest issue when scanning; specially when I'm in a brick-and-mortar bookshop.

I'll get back to you in a bit.

**Comment by tfonteyn** [comment]
the actual decoding is by and large the same. Not much of a surprise, as we both interface with Zxing after all.

Th biggest difference I can find is that I depend on the camera doing the focusing on its own, while Atharok  uses a specific auto-focusing helper. He also supports zooming, but that is really just a matter of holding the camera closer to the code.

I've added auto-focussing to my scanner code and will run some tests on a real device.

**Comment by tfonteyn** [comment]
I don't see any difference on my test device, but obviously it will all depend on the camera.

My scanner code is a separate module/project to facilitate testing.
I've pushed a build of my scanner library/test project here:

https://github.com/tfonteyn/TinyZXingWrapper/releases/tag/v1.1.1

If you could install that apk, you'll get a basic scanner example.

The main thing to test using the "Generic" scan, but do it with the auto-focus switch ON (default) and OFF.

Let me know if you get a different result when it's ON.

Likewise, play with switching the torch OF/OFF.

I presume when you said "My camera is not detecting the barcodes" you mean it just never detects/scans a number, and NOT that it scans it but delivers a wrong result? Can you confirm this presumption?

Does it scan no codes at all, or is it a matter that some work, other not?
If the latter, can you upload a picture of such a failing scan?

**Comment by stacsk** [comment]
> My camera is not detecting the barcodes

Hi. I meant it never detects anything.

I tried it with several books/magazines now. The main app and the separate scanner detects barcodes wider than 2.5 cm at 10 cm length between the camera and the book, however it's very slow and sometimes it can't detect the same barcode at the same settings, also it sometimes gives the wrong barcode, sometimes the right one for the same book. Also, barcodes with 2cm width can't be scanned at all.

I've tried it with auto-focus on and off and it's pretty much the same. Both apps perform similarly. Meanwhile with Atharok's scanner it takes less than half a second.

I think it could be related to the lack of zoom, the camera has just too much space to study and when you bring the camera closer, the barcode naturally gets blurred and becomes unreadable.

**Comment by tfonteyn** [comment]
>  10 cm length between the camera and the book

to b honest, that's the distance I tend to scan my own books. At home I'm typically using a tablet with a single lens.

> bring the camera closer, the barcode naturally gets blurred and becomes unreadable.

yes, this bit is normal, the camera can't focus when it's too close, or is brought too close too fast.

> it's very slow 

That I have come across myself; not too often, but I have not investigated really. I'll add this to the to-do.

> sometimes gives the wrong barcode

personal experience that's almost always down to lightning. Enabling the torch rectifies this.

>  auto-focus on and off 

yes, didn't make any difference for me either.

> the camera has just too much space to study

quite possible.

ok - this was good feedback. I've got work to do, that's clear :)

Could you please provide:
- brand/model of the device you're using? I tend to check specs on https://www.gsmarena.com
- can you upload a picture of a book (the barcode) which totally fails to scan

My scanner code is quite some years old and at the time I might not have done a good job of optimizing. I'll revisit and see what I can do this week.

**Comment by stacsk** [comment]
>    * brand/model of the device you're using? I tend to check specs on https://www.gsmarena.com

I'm using Xiaomi Note 12 Pro+, Android 13.

>     * can you upload a picture of a book (the barcode) which totally fails to scan

This book is from a series that have the same barcode width for every book. I couldn't scan this until just now when I tried for one more time, and it gave me the correct barcode. It's difficult to scan the book in this series. This one is Emile Zola - Nana (publisher: Türkiye İş Bankası Kültür Yayınları). Mind you that it scans perfectly fine on these photos since the pictures are bigger, and so are the barcodes.

![Image](https://github.com/user-attachments/assets/a0d8c0d3-1a78-4d58-9154-62100e1cf870)
![Image](https://github.com/user-attachments/assets/ad5a0290-9229-4256-bd90-0e2ca70ec243)

The dimensions of the book are 12.5 x 20.5 cm if you wanna scale the pictures to your screen.
Thanks again for your good work.

**Comment by tfonteyn** [comment]
I may unexpectedly already have some news... it's not the zoom, but it's related.

It's the size of the preview. Mine: full screen; Atharok's a small rectangle.

Funnily enough I had already implemented most/all of the code to use an *embedded* preview/scanner. i.e. pretty much like what that app does. I just had not enabled it in a release build.

I ran a quick test with the embedded preview and it's already much faster.

If you're into the tech/code bits, take a look [here](https://github.com/tfonteyn/NeverTooManyBooks/blob/a92c82336a8845530cba2788845f6974b6a7d231/app/src/main/java/com/hardbacknutter/nevertoomanybooks/search/SearchBookByIsbnFragment.java#L242C43-L242C44) and the use of that *embeddedBarcodeScanner* switch.

So.... I'll likely enable that *embedded* preview permanently and run my usual tests. I may have to tweak the screen layouts a bit for smaller devices. No promise on a release date, but it shouldn't take too long providing I hit no major issues.

**Comment by stacsk** [comment]
That's what I was actually trying to say when I said zoom. I'm glad you worked it out. I don't know how to code/compile but I'll keep an eye out for the next update. Yay!

**Comment by tfonteyn** [comment]
yes - that's what put me on the right track.

One thing the embedded scanner code is still missing is the torch-button. I'll need to do that first, then start the tests.

But enough for today - dinner time :)

**Comment by tfonteyn** [comment]
I've wrapped up a new version of the scanner example, can you please give this a try to see if your issues are indeed fixed?

https://github.com/tfonteyn/TinyZXingWrapper/releases/download/v1.2.0-beta/example-1.2.0-beta.apk

Test using the "Generic" scan button.

**Comment by stacsk** [comment]
It scanned 4 books correctly, and 5 wrong. I also couldn't scan small barcodes still, the ones I mentioned before. I thought you were considering adding a smaller canvas, and/or zoom for that.

These are the ones that failed:
9789750809958 detected as 108770209958
9786055272296 detected as 06291686
978605594393 detected as 11284846
9789754713435 detected as 108774113435
9199753618271 detected as 7171816455995

![1755339227359.jpg](https://github.com/user-attachments/assets/fe22a811-0abe-4963-a2e1-6b292fb33bc3)

![1755339195427.jpg](https://github.com/user-attachments/assets/544baaa1-ac2c-4172-a752-dbcba43106e6)

![1755339293893.jpg](https://github.com/user-attachments/assets/7b686933-e74c-4c01-a03b-15bce2ff5190)

![1755339270188.jpg](https://github.com/user-attachments/assets/bdf26bb3-dabf-43ac-84d8-a33c3ebd4054)

![1755339249104.jpg](https://github.com/user-attachments/assets/a06405f1-0006-4729-9a5b-d9fdd847da75)

**Comment by tfonteyn** [comment]
>  I thought you were considering adding a smaller canvas

? that's what I did exactly? Are you sure the updated app was installed? Please make sure to remove the first test-app, and install the new version from scratch.

https://github.com/tfonteyn/TinyZXingWrapper/releases/download/v1.2.0-beta/example-1.2.0-beta.apk

This is a screenshot, which shows the smaller canvas. (ignore the image on the canvas, that's just emulator junk)

<img width="733" height="1680" alt="Image" src="https://github.com/user-attachments/assets/3348d399-2d1a-41a1-8748-08f37e7e9b94" />

**Comment by tfonteyn** [comment]
side note: I'm hitting a known bug with the PreviewView canvas/surface; hence the delays.

also: I just deployed the 1.2.0-beta testapp on my actual device, and scanned those failing barcodes you posted straight from the screen. They all scanned first-time ok. This is of course not the same as scanning from paper with different lightning, but at least it proves the actual decoding is working fine. The main difference remains the camera, so further tuning might be needed; but please check the updated app first

**Comment by stacsk** [comment]
> ? that's what I did exactly? Are you sure the updated app was installed? Please make sure to remove the first test-app, and install the new version from scratch.

I have the 1.2 that you just posted, I was just thinking you'd narrow the scanning area, and make it much like a square, the way it is in Atharok's. Maybe that'd improve it.

If anyone else is having the problem with scanning, please give this a thumbs up.

**Comment by tfonteyn** [comment]
Now I'm confused 😕 

> I was just thinking you'd narrow the scanning area.

The scanning area (preview) went from full-screen to a rectangle approximately a quarter of the screen-height.
(rectangle/square is not important - it's the size).

Are you saying you don't get the smaller rectangle ? And are still full-screen? Can you upload a screenshot of your device while in scan-mode?

> If anyone else is having the problem with scanning, please give this a thumbs up.

yes, absolutely - anyone else seeing this, let me know.

**Comment by mobrcian** [comment]
Scanning under Generic and Product works quickly and without problems.
Front camera scanning is not working, QR code scanning works.

**Comment by stacsk** [comment]
> Are you saying you don't get the smaller rectangle ? And are still full-screen? Can you upload a screenshot of your device while in scan-mode?

Mine is the same that's in your screenshot; it's the latest version that you linked today. Maybe the size is still too big for smaller barcodes, since they're still not being detected. The solution might be a) making the area smaller than it currently is, and/or b) adding a zoom feature which will prevent the blurring issue as you get closer. I personally don't understand how Antharok made it work, but whatever they did, it works.

**Comment by ChristianGruen** [comment]
> If anyone else is having the problem with scanning, please give this a thumbs up.

I have installed https://github.com/tfonteyn/TinyZXingWrapper/releases/download/v1.2.0-beta/example-1.2.0-beta.apk. It looks like the screenshot, and the barcode is recognized very quickly and correctly as soon as I move the camera further down:

<img width="135" height="300" alt="Image" src="https://github.com/user-attachments/assets/ca04a3a3-e3d1-4be3-acad-41064506b770" />

I don’t have any problems with the integrated scanner either:

**Comment by tfonteyn** [comment]
@mobrcian 

> Front camera scanning is not working

yes, I just noticed that myself - to be honest, I can't even remember when I last tested front-camera; must have been from I wrote this scanning code several years ago now. I'll revisit this later, it's of lesser importance for now.

**Comment by tfonteyn** [comment]
I've done more optimizations and code changes, some replacements of my own code by the system code (LuminanceSource handling for the techs here). I've also re-added the auto-focus switch.

(And unrelated while I was at it, updated the result-point display, those dots that flicker, to be more accurate)

No changes to front-camera use.

Can you please replace/load the new version of the test app:

https://github.com/tfonteyn/TinyZXingWrapper/releases/download/v1.2.0-beta2/example-1.2.0-beta2.apk

Again, try "generic" with and without switching on auto-focus and let me know the results.

**Comment by stacsk** [comment]
The ones it didn't scan before can be scanned with this version. It still scanned slow and 1 out of 4 times it gave the wrong barcode, 1 out of 4 didn't scan (for 5-6 seconds), other times it worked without a problem. Flash didn't make much difference most of the times.

One thing I noticed, the app I mentioned launches with some zooming in by default, which is lacking in this demo.

Auto-focus off didn't produce results mostly, or were wrong.

**Comment by tfonteyn** [comment]
>  some zooming in by default, which is lacking in this demo.

correct, I typically try to make once change at a time which makes it a lot easier to determine *which* change does *what*.
The big difference today which needed testing was how camera-rotation & luminescence is handled (previous: my code; now: Android internals). Other optimizations were not directly related, but too obvious (now) to skip.

> The ones it didn't scan before can be scanned with this version.

ok, at least this is progress.

> It still scanned slow 

Well, with the smaller preview I can see a significant performance increase on my devices, but as said before, this will depend on the actual camera.

>  It still scanned slow and 1 out of 4 times it gave the wrong barcode, 1 out of 4 didn't scan (for 5-6 seconds),

ok, I'll keep working :)

> Auto-focus 

I actually saw differences myself when testing on my phone.
I test the barcode scanner typically on both my tablet (single-lens, no zoom, no torch) and my phone (bells-and-whistles).
First round of tests of the auto-scan a couple of days ago were on my tablet and saw little to no difference.
Today I used my phone, and with auto-scan it was clearly faster (even faster than the already faster 'small-preview' gains).

**Comment by stacsk** [comment]
Great to see progress. I forgot to mention, the small barcode books (the one in the [pics]()https://github.com/tfonteyn/NeverTooManyBooks/issues/181#issuecomment-3180450530) still couldn't be scanned. They're the ones with 2cm width.
Thank you for the cool work.

**Comment by tfonteyn** [comment]
done some googling, just note-keeping, no conclusion yet and some of these will obviously not be relevant.

https://github.com/Redth/ZXing.Net.Maui/issues/82
https://stackoverflow.com/questions/62561857/zxingscannerview-not-run-on-xiaomi-device
https://github.com/Redth/ZXing.Net.Maui/pull/202

**Comment by tfonteyn** [comment]
what bothers me the most is the point of error. The flow is:

1. camera streams video
2. video is converted to a snapshot in [YUV ](https://en.wikipedia.org/wiki/Y%E2%80%B2UV) format.
3. snapshot converted to a bitmap
4. bitmap passed to the barcode decoder.
5. barcode

The big question I still face....  between which above steps are we 'breaking'. 
Today's improvements focussed on step 1 (auto-focus) and step 2->3 (optimizations as mentioned earlier).
Step 4->5 is stable; I mean.. I literally have scanned thousands of books, and presumable so have other users.

**Comment by tfonteyn** [comment]
@mobrcian 

Turns out the front camera **is** working... but is unreliable. Mine has a difficult time focussing, and when it does, the decoding goes more wrong then right. So technically speaking "it's working" but "it's [bleeped]" 👎  I suppose most front cameras are simply not made for such tasks. I should probably remove the option to use it altogether.

**Comment by mobrcian** [comment]
I agree with the last sentence.
I only tested the functionality of the app when this option was available 🙂

**Comment by tfonteyn** [comment]
time for another test if you don't mind?

https://github.com/tfonteyn/TinyZXingWrapper/releases/download/v1.2.0-beta4/example-1.2.0-beta4.apk

what's new:
- the preview is now centring the video-stream. You may not have seen an issue, but there were problems in this area.
- internally step 2 (video -> yuv) is now cropping the incoming image to limit the amount of work the decoder needs doing.
- extra debug options:
  - "try harder":  sounds a bit silly, but this is a ZXing option forcing it to process more of the image area.
  - also try-inverse:  added for completeness, but unrelated to your issues. This is for white-barcodes printed on a black background; so do not enable this unless you want to test such a barcode.

Can you please test with:
1 auto-focus ON,     try-harder OFF and "Generic"
  => this will test the new cropping logic
2 auto-focus ON,  try-harder ON and "Generic" 
  => I suspect this will be no different from 1.

if neither of the above are an improvement, repeat with auto-focus OFF for completeness sake.

**Comment by stacsk** [comment]
**### a. AF on TH off generic:**
Book 1 (momo)
attempt 1: wrong barcode, slow
attempt 2: true barcode, fast
attempt 3: wrong barcode, fast
attempt 4: true barcode, fast
attempt 5: true barcode, fast
attempt 6: wrong barcode, fast

Book 2 (small barcode book)
1: fast, wrong
2: slow, wrong
3: slow, wrong
4: fast, wrong

Book 3 (epsilon)
1: slow, true
2: slow, true
3: fast, true
4: slow, true

**### b. AF on TH on generic:**

Book 1 (momo)
1: fast, wrong
2: fast, wrong
3: fast, wrong
4: fast, wrong
5: fast, wrong

Book 2 (small barcode book)
From 5th attempt on, I moved the cam to the edge of the book so it wouldn't mix the barcode with [this ](https://geoim.bloomberght.com/2018/01/01/ver1514793509/2082852_720x360.jpg)thing. It still made mistakes and gave a number composed of 8 digits.
1: fast, wrong
2: fast, wrong
3: undetected
4: fast, wrong
5: fast, true
6: fast, true
7: fast, true
8: fast, wrong
9: fast, wrong

**### c. AF off TH off generic**
Book 1
1: fast, wrong
2: fast, true
3: fast, true
4: fast, wrong (only missed it with one digit)
5: slow, wrong (8 digit)
6: slow, wrong (8 digit)

Book 2
1: fast, true
2: fast, true
3: fast, wrong (8 digit)
4: slow, undetected
5: fast, true
6: fast, true
7: slow, wrong

Book 3:
1: fast, true
2: fast, true
3: fast, true
4: slow, undetected
5: fast, true
6: slow, true

Here are some other attempts after the above. Green is Book 1, white is Book 2, orange is Book 3.
https://github.com/user-attachments/assets/ec836641-7cf3-42e6-b17a-ee7f39a3b79c

https://github.com/user-attachments/assets/a7073c1d-ffa8-4b6e-8d76-baa2ae36bd10

**Comment by tfonteyn** [comment]
ok - thanks for those results.

I've added zoom functionality now. Please give it a try:

https://github.com/tfonteyn/TinyZXingWrapper/releases/download/v1.2.0-beta5/example-1.2.0-beta5.apk

**Comment by stacsk** [comment]
The zoom definitely helps. When I launch the scanner with 65% zoom (at 15-20 cm distance) it doesn't even need auto-focus or try-harder, it just scans instantly and correctly. 

Side note, in some sessions when I set the zoom to 0-15%, when it doesn't scan one book, it won't detect any other book either so you have to go back and open the scanner again.

The video is not very important since it's lower than 65% zoom. As I said, that solves the problem for the most, if not all. The barcode for this is 978944887014.
https://github.com/user-attachments/assets/a4fddabf-f51f-4a90-a815-bda60ceb0bd9

The second video is 65% zoom, I left the toggles off unless needed. As you see, when it doesn't detect, I just launch it again and it works. I don't know if you can read the results but all but one (which I highlighted at the end) is correct.

https://github.com/user-attachments/assets/2e7ce0e0-54d9-4c70-93ac-54fc90eb375d

**Comment by tfonteyn** [comment]
brilliant - glad we got there.

All in all this has been good. I not only managed to get your setup finally working, but the overall behaviour of the scanner has certainly improved for myself and others as well.

Now I need to integrate this in the NTMB app.

I'll keep you posted!

cheers!

**Comment by stacsk** [comment]
Thanks a bunch! ^^

**Comment by tfonteyn** [comment]
integration was finished earlier yesterday, but there is a slight delay as I found I need to tune the screen layouts to different device sizes more than I expected.

**Comment by tfonteyn** [comment]
here you go: [7.8.0](https://github.com/tfonteyn/NeverTooManyBooks/releases/tag/v7.8.0)

The zoom slider is hidden by default. Check out the [docs](https://github.com/tfonteyn/NeverTooManyBooks/wiki/Home/_edit#barcode-scanning) for the options.
